include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - publish

test-unit:
  stage: test
  image: bitnami/dotnet-sdk:6
  script:
    - dotnet test --collect "XPlat Code Coverage"
    - mkdir coverage
    - cp TestResults/*/coverage.cobertura.xml coverage/cobertura-coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

test-lint:
  stage: test
  image: bitnami/dotnet-sdk:6
  script:
    - dotnet format --verify-no-changes

publish-nuget:
  stage: publish
  rules:
    - if: $CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG =~ /^v/
  image: bitnami/dotnet-sdk:6
  script:
    - >
        dotnet pack 
        --configuration Release
        --property Version=${CI_COMMIT_TAG:1}
        --property FileVersion=${CI_COMMIT_TAG:1}.${CI_JOB_ID}
    - >
        dotnet nuget push
        --api-key $NUGET_API_KEY
        --source https://api.nuget.org/v3/index.json 'bin/Release/*.nupkg'
