variables:
  # from https://semver.org/
  SEMVER_REGEX: >
    ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - publish

test-spec:
  stage: test
  image: bitnami/dotnet-sdk:6
  script:
    - >
        dotnet test
        --configuration Release
        --collect "XPlat Code Coverage"
    - mkdir coverage
    - cp Goodrouter.Spec/TestResults/*/coverage.cobertura.xml coverage/cobertura-coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

test-lint:
  stage: test
  image: bitnami/dotnet-sdk:6
  script:
    - >
      dotnet format
      --verify-no-changes

publish-nuget:
  stage: publish
  rules:
    - if: $CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG =~ /^v/
  image: bitnami/dotnet-sdk:6
  script:
    # see https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/versioning 
    - >
        dotnet pack Goodrouter
        --configuration Release
        --property Version=${CI_COMMIT_TAG:1}
        --property AssemblyVersion=$(echo ${CI_COMMIT_TAG:1} | perl -pe "s/$SEMVER_REGEX/\1.0.0.0/")
        --property FileVersion=$(echo ${CI_COMMIT_TAG:1} | perl -pe "s/$SEMVER_REGEX/\1.\2.\3.${CI_JOB_ID}/")
    - >
        dotnet nuget push
        --api-key $NUGET_API_KEY
        --source https://api.nuget.org/v3/index.json 'Goodrouter/bin/Release/*.nupkg'
