on: 
  - push
  - pull_request

jobs:

  test-spec:
    runs-on: ubuntu-latest
    container: bitnami/dotnet-sdk:6
    steps:
      - uses: actions/checkout@v3
      - run: dotnet test

  test-lint:
    runs-on: ubuntu-latest
    container: bitnami/dotnet-sdk:6
    steps:
      - uses: actions/checkout@v3
      - run: dotnet format --verify-no-changes
